lints.workspace = true

[package]
name = "slot-arithmetic"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
rust-version.workspace = true

[dependencies]
hex.workspace = true
minicbor = { workspace = true, features = [ "alloc" ] }
serde = { workspace = true, features = [ "std", "derive" ] }
thiserror.workspace = true
proptest = { workspace = true, optional = true, features = [ "std" ] }

[dev-dependencies]
proptest = { workspace = true, features = [ "std" ] }

[features]
test-utils = ["proptest"]
