blank_issues_enabled: true
contact_links:
  - name: Amaru Website
    url: https://amaru.global
    about: Looking for high-level information about Amaru? The official website shall help.

  - name: Amaru Twitter/X
    url: https://x.com/amaru_cardano
    about: Wanna draw our attention about something? Tag us @amaru_cardano!

  - name: PRAGMA Discord
    url: https://discord.gg/Zbbumu9NMz
    about: If you rather chat with maintainers and the community, Discord is the place.
