[package]
name = "amaru-examples-shared"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true

publish = false

[dependencies]
amaru-kernel = { path = "../../crates/amaru-kernel" }
amaru-ledger = { path = "../../crates/amaru-ledger" }
amaru-plutus = { path = "../../crates/amaru-plutus" }
amaru-stores = { path = "../../crates/amaru-stores", default-features = false }
hex.workspace = true
