# Find the full list of available options here: https://doc.rust-lang.org/cargo/reference/config.html

[alias]
fmt-amaru = "fmt --all -- --check"
clippy-amaru = "clippy --workspace --all-targets --all-features -- -D warnings"
check-amaru = "check --workspace --all-targets --all-features"
build-amaru = "build --workspace --all-targets --all-features"
test-amaru = "test --workspace --all-targets --all-features"
deny-amaru = "deny check licenses --config .cargo/deny.toml"

[env]
CLIPPY_CONF_DIR = ".cargo"

[build]
rustflags = ["--cfg", "tracing_unstable"]
