[package]
name = "amaru-ledger"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
rust-version.workspace = true

[dependencies]
ouroboros = { path = "../ouroboros" }
async-trait.workspace = true
gasket.workspace = true
hex.workspace = true
num = { version = "0.4.3", features = ["num-bigint"] }
pallas-addresses.workspace = true
pallas-codec.workspace = true
pallas-crypto.workspace = true
pallas-primitives.workspace = true
pallas-network.workspace = true
tokio.workspace = true
tracing.workspace = true
vec1 = "1.12.1"
serde.workspace = true
bech32 = "0.11.0"
opentelemetry.workspace = true
once_cell = "1.20.2"
miette.workspace = true
thiserror.workspace = true

[dev-dependencies]
proptest.workspace = true
envpath.workspace = true
insta.workspace = true
