lints.workspace = true

[package]
name = "amaru-consensus"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
rust-version.workspace = true

[dependencies]
pallas-codec.workspace = true
pallas-crypto.workspace = true
pallas-math.workspace = true
rayon.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true

amaru-kernel.workspace = true
amaru-ouroboros.workspace = true
amaru-ouroboros-traits.workspace = true
slot-arithmetic.workspace = true

[dev-dependencies]
envpath.workspace = true
hex.workspace = true
insta.workspace = true
proptest.workspace = true
rand.workspace = true
tempfile.workspace = true
